### ISSUE TITLE
Question - Standalone mode, Stealth Chop,

### ISSUE THREAD

**Issue by adam120800** [TheFeralEngineer/Klipper-for-Elegoo-Neptune-series-3D-Printers#17]
Are the drivers running in Standalone mode or UART. If they are standalone does that mean they have stealthchop enabled by default? 

Probably a question for klipper community; Is the default Current for steppers set to 0.8A for a TMC2208 / TMC2225? Thanks!

**Comment by HinataKato** [comment]
It's on Standalone mode, and the stealthchop are enabled by default.
The current of 0.8A from my personally think, it's kinda sweat point (I had my 2208 on 0.7 though)
