### ISSUE TITLE
Neptune 3 Plus Config Changes

### ISSUE THREAD

**Issue by BongoEADGC6** [TheFeralEngineer/Klipper-for-Elegoo-Neptune-series-3D-Printers#2]
In case anyone is looking for answers in this repo. 

The communications settings for the Neptune 3 Pro firmware doesn't work for the Neptune 3 Plus. In order for the Neptune 3 Plus to operate it must use USART2 PA3/PA2 for connectivity.

**Comment by TheFeralEngineer** [comment]
Good to know! I'll pop out a bin file for it asap

**Comment by BongoEADGC6** [comment]
Only problem at the moment is figuring out the printer.cfg regarding the axes and offsets. Having a difficult time getting those solved at the moment.

**Comment by jdoncouse** [comment]
I have the N3Pro USB firmware loaded right now on my plus and it's working just as well as my pro as far as i can tell. 

I did have the issue described in this post.
https://www.reddit.com/r/klippers/comments/ybqvse/trouble_connecting_to_mcu_mks_gen_l_10/

sudo systemctl stop brltty-udev.service
sudo apt remove brltty
fixed the issue on a fresh install of Pop!_OS

**Comment by 3Dtcb** [comment]
> 

Any chance to get the updated firmware for the N3Plus?

**Comment by TheFeralEngineer** [comment]
> > 
> 
> Any chance to get the updated firmware for the N3Plus?

The bin file should work with all models of Neptune 3

**Comment by 3Dtcb** [comment]
> > Any chance to get the updated firmware for the N3Plus?
> 
> The bin file should work with all models of Neptune 3

I thought you said that a new bin file is needed in february?

**Comment by 3Dtcb** [comment]
If someone else reads this ... I found the solution because I made 2 mistakes.

1. Use the "Serial UART communication" firmware for the Neptune 3 Plus
2. Use the upper usb port of the sonic pad (RTF! I know ...)

Maybe this information will avoid stupid questions like mine in the future.
